### ISSUE TITLE
👍 恭喜完成 !!! 有些地方想聊聊

### ISSUE THREAD

**Issue by Azraeil** [op880623/dindrink#1]
有幾個地方想討論：
## 上傳圖片部分：
1.上傳到 heroku 的圖片不久後會消失
>![image](https://user-images.githubusercontent.com/30717954/36818789-a0c16a2e-1d21-11e8-96a6-f741b37be8af.png)

目前已知解法：
a. 換其他可上傳保留貼圖的空間/雲端硬碟
b. 換 gem , `filestack`
>[來源討論串](https://goo.gl/NyUzf6)，有其他串比較詳細的 但是我沒按到 follow 

c. 找方法讓 heroku 不睡著，這部分我之後應該會練習 哈。

---
2.上傳後的圖片似乎會被拉大?
>![image](https://user-images.githubusercontent.com/30717954/36818857-f5c86c98-1d21-11e8-964a-9044250e1086.png)

---
3.好像沒有明確告知上傳的是菜單照片 XD
>![image](https://user-images.githubusercontent.com/30717954/36819682-5ba95d80-1d25-11e8-8ba8-dffb851a0d34.png)

---
## 使用者權限部分
目前應該是所有使用者都能創建 + `刪除` 所有飲料店?

哦，更正，delete 按鈕應該是誤植?
我按了自己創的也沒反應，所以是沒實作功能的按鈕?

---
## 資料驗證部分
1.無意中試到的，飲料杯數 9999999999，會觸發：
> ![image](https://user-images.githubusercontent.com/30717954/36819988-ae8b50b6-1d26-11e8-8eb0-4d43d89469a8.png)

---
2.目前 `統計` 似乎沒有總價格/小計欄位？
`誰買甚麼`，買了幾杯總共該付多少錢？

---
3.從訂飲料系統 轉變成便當店 或其他店 應該可行
版面一樣，一些欄位跟配置根據使用者選擇的類型調整一下
EX：建立店面時有類型可以選擇：飲料店，便當店，速食店...。

抱歉，問題很多哈  

我之後應該也會練習寫個水電費瓦斯房租雜費 app 給我跟我的室友用 XD
不然算錢的時候還真的挺麻煩的

加油!!!

**Comment by op880623** [comment]
##上傳圖片部分：

1.我只知道在後端傳的話一開始就傳不上去，我不知道前端傳的一段時間後會被刪除。我再看怎麼處理。

2.沒錯，css寫出來的結果就是這樣，因為我找到的圖都是比範圍更大的，所以沒注意到小圖會變大。一樣會再處理。

3.這是我的錯，沒有說清楚。

##使用者權限部分：
那個刪除其實是刪除訂單的意思，所以你把訂單網址記下來，刪掉再進去會導回首頁。你每次在首頁點訂飲料進去的都是新的網址，因為是不同的訂單。所以這也是我沒有說清楚。抱歉。

##資料驗證部分：
1.我沒試到這個，我再去了解。

2.我統計的目的是方便打電話訂飲料的時候不用自己統整，然後可以`照著念給店員聽`，因為這才是飲料累計最常發生的時候。
一個人定多種多瓶飲料較少且數量不多，所以暫時不想做，我還想過要加checkbox記付錢沒。

3.一開始也想過要混著做，然後就發現還是不要貪心，先做好一個再說XD

**Comment by Azraeil** [comment]
#上傳圖片部分
> 找不到 github 要怎麼引言

其實我看不完全清楚後端跟前端的上傳圖片的方式。
後端是指從 git push heroku master 這樣子嗎？
然後前端就是透過你的頁面 "選擇檔案" ？

---
# 使用者權限部分
原來你有做！！！我眼花沒看清楚，我有一點點印象網址是亂碼，哈

---
# 資料驗證部分
瞭解！

最後，不用道歉啦，哈

我現在正爲了學習關聯(Self-referential Relationships 自關聯 或 Self Joins 自連接)
的教材命名頭痛 OTL

爲什麼要把追蹤記錄取名叫 followship，而不叫 followrecord
然後被追蹤的人叫 following，不叫 follower

我都有特地再拿單字去 google 過，還是我英文真的太爛(笑。
